swagger: '2.0'
info: # This line should have no indentation
  title: Example yaml.spec
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert('textarea') src=1>"></form>
paths: # This line should also have no indentation, same level as swagger and info
  /accounts:
    get:
      responses:
        '200':
          description: No response was specified
      tags:
        - accounts
      operationId: findAccounts
      summary: Finds all accounts
